### ISSUE TITLE
Deploy Operations So SLOOOOOW... and Timeouts

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Deploy.Issues#106]
On an Umbraco 9.4.1/Deploy 9.3.1 site, sometimes transferring a single content node (without many dependencies) from local to Cloud is painfully slow - resulting in an "Abort remote session" Timeout error.

Sometimes this is fixed by Restarting the local and/or remote environments. Sometimes not. 

**Is it just me?**

Also, sometimes when I do a "Schema Deployment from Files" on the Cloud environment, it will take a really long time (like 10 minutes), as if it's hanging somehow, then sometimes report a failure with no Exception in the Log.

Sometimes the process just hangs - never returning a completion or failure.  Sometimes I see an odd error:

```
System.InvalidOperationException: Recursive locks not allowed
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentStore.Lock(WriteLockInfo lockInfo, Boolean forceGen)
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentStore.ScopedWriteLock..ctor(ContentStore store, Boolean scoped)
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentStore.<GetScopedWriteLock>b__27_0(Boolean scoped)
   at Umbraco.Cms.Core.Scoping.ScopeContextualBase.Get[T](IScopeProvider scopeProvider, String key, Func`2 ctor)
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentStore.GetScopedWriteLock(IScopeProvider scopeProvider)
   at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.Notify[T](ContentStore store, JsonPayload[] payloads, Action`4 action)
   at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.Notify(JsonPayload[] payloads)
   at Umbraco.Cms.Core.Cache.ContentTypeCacheRefresher.<>c__DisplayClass10_0.<Refresh>b__6()
   at Umbraco.Extensions.PublishedModelFactoryExtensions.WithSafeLiveFactoryReset(IPublishedModelFactory factory, Action action)
   at Umbraco.Cms.Core.Cache.ContentTypeCacheRefresher.Refresh(JsonPayload[] payloads)
   at Umbraco.Cms.Infrastructure.Sync.ServerMessengerBase.DeliverLocal[TPayload](ICacheRefresher refresher, TPayload[] payload)
   at Umbraco.Cms.Infrastructure.Sync.ServerMessengerBase.Deliver[TPayload](ICacheRefresher refresher, TPayload[] payload)
   at Umbraco.Cms.Infrastructure.Sync.ServerMessengerBase.QueueRefresh[TPayload](ICacheRefresher refresher, TPayload[] payload)
   at Umbraco.Cms.Core.Cache.DistributedCache.RefreshByPayload[TPayload](Guid refresherGuid, IEnumerable`1 payloads)
   at Umbraco.Extensions.DistributedCacheExtensions.RefreshContentTypeCache(DistributedCache dc, ContentTypeChange`1[] changes)
   at Umbraco.Cms.Core.Cache.DistributedCacheBinder.Handle(ContentTypeChangedNotification notification)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at Umbraco.Deploy.Infrastructure.DeployScopedNotificationPublisher.HandleNotifications()
   at Umbraco.Deploy.Infrastructure.DeployScopedNotificationPublisher.ScopeExit(Boolean completed)
   at Umbraco.Cms.Core.Scoping.Scope.<>c__DisplayClass106_0.<RobustExit>b__1()
   at Umbraco.Cms.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Cms.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Cms.Core.Scoping.Scope.TryFinally(Action[] actions)
   at Umbraco.Cms.Core.Scoping.Scope.RobustExit(Boolean completed, Boolean onException)
   at Umbraco.Cms.Core.Scoping.Scope.DisposeLastScope()
   at Umbraco.Cms.Core.Scoping.Scope.Dispose()
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem.ExecuteAsyncSub(IWorkContext context, List`1 resume, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)
```

The only way to resolve that is to restart the Cloud environment.

**Comment by hfloyd** [comment]
Additionally, sometimes after I attempt to push a larger quantity of content nodes (perhaps a "node+descendants" situation), which results in a Timeout, I find that the remote server (on Cloud) is now returning "service unavailable" on the site as a whole, which is a really bad consequence of trying to use Deploy.

**Comment by hfloyd** [comment]
I just had the "recursive locks" error again, so have created a separate issue for that -https://github.com/umbraco/Umbraco.Deploy.Issues/issues/108

**Comment by Abrissirba** [comment]
My experience is similar with "Update Umbraco Schema From Data Files". We are running on-prem. The deployment can take up to 15 minutes and during that time the site is partly unresponsive and gives timeout exceptions. 

I am missing some kind of log/progress of what the deployment is doing. Is it possible to log what the deployment is doing? Is the architecture of deploy documented somewhere to give an understanding of what it is that makes the deployment so slow?

**Comment by AndyButland** [comment]
Please see some updates related to this in [this comment](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/128#issuecomment-1425612448) on another issue.

I'll close this as the updates in the releases indicated will address and improve this situation.  Of course if having updated and if not finding a resolution please feel free to re-open or create a new issue.
