### ISSUE TITLE
Unhelpful error when trying to restore content with a trashed image

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Deploy.Issues#111]
When restoring content from Umbraco Cloud, if there is a trashed image referenced by a content item the error message is not at all helpful, and gives no indication as to the true problem:

> System.Net.Http.UnsupportedMediaTypeException: No MediaTypeFormatter is available to read an object of type 'Boolean' from content with media type 'text/html'.
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<WaitAction>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<CreateManifestAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<CreateManifestOnSource>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetPartialRestoreWorkItem.<Proceed>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetPartialRestoreWorkItem.<ExecuteAsyncSub>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.TargetPartialRestoreWorkItem.<ExecuteAsyncSub>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetPartialRestoreWorkItem.<ExecuteAsync>d__14.MoveNext()

Reproduction
------------

### Bug summary

I'm using Umbraco 8.17.2 with Deploy 4.4.4.0 on Umbraco Cloud, restoring to a local environment on my laptop. My document type has a block list editor, and one of the blocks has an image data type. A content node is created at the site root (alongside a 'home page' root item) and an image is selected and saved. The image is then deleted, meaning it's moved to the recycle bin.

The editor for my block looks like this:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/1260550/164801359-fe62874b-2a32-41b2-a6ad-0a334821520e.png">

I then try to initiate a restore of the specific content node, or all content, from my local site. It fails with the above error.

If I remove the image and replace it with one that is not deleted, then retry the restore, it works.

### Expected result

Either the content is restored with the image removed, or a helpful error message is displayed - something like "The content with name {name} and id {id} could not be restored as it has an image selected that is in the recycle bin. Remove the image from the page, or restore it from the recycle bin, and try again."

### Actual result

<img width="375" alt="image" src="https://user-images.githubusercontent.com/1260550/164801531-426a8ee9-eb5c-43fe-846d-09dee9c8c931.png">

**Comment by AndyButland** [comment]
I've tried to replicate this - with 4.5.0, due out on Tuesday - though I wouldn't expect any differences in behaviour here.

I get an expected error message with this scenario:

![image](https://user-images.githubusercontent.com/1993459/164895033-833023a9-ad58-4f0b-8187-e26818b61237.png)

So not sure if there's something else going on here, or whether this has been resolved.

Can I ask please if you could try again though after upgrading to 4.5 and see if you have the same issue, and if so, share with us the `.uda` files for your doc and data types that should allow recreation of your setup and replicate of the issue?  Thanks.

**Comment by sussexrick** [comment]
My Umbraco Cloud site is still showing Deploy 4.4.4.0 but I can point you to [my uda files](https://github.com/stoolball-england/stoolball-org-uk/tree/master/Stoolball.Web/data/revision).

**Comment by AndyButland** [comment]
I'll close this one now having previously and again tried to replicate and not been able to replicate this problem with a later version of Deploy than you were using when the issue was raised.  Please do re-open though if you can replicate the error with the latest version of Deploy 4, 9 or 10, and if so, if you can provide details of a minimal document type structure that causes the problem and set of steps to replicate, that will be useful.  Thanks.
