### ISSUE TITLE
UDA file replaced  by a partial error message

### ISSUE THREAD

**Issue by jemayn** [umbraco/Umbraco.Deploy.Issues#164]
I recently updated a property description on a document type. Now my UDA file has an update where it's replaced by a stacktrace.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

I've created my own simple property editor. The datatype is serialized into a UDA file just fine.
The doctype the property is included on was serialized just fine.

After updating the description on the doctype I get a new doctype change like this:
![image](https://user-images.githubusercontent.com/79840720/235622147-c2794e67-3204-48af-84a4-88fbea20bb35.png)

Removing the description and doing a new full uda export via the Deploy dashboard doesn't help so I don't think the description is the underlying cause.

Not really sure where to look or what to do to debug this.

### Specifics

**Versions**:
Umbraco 11.2.1
Deploy 11.0.2

Full stacktrace in the deploy file is this - no errors in the deploy log only inside the uda file:
```
    "StackTraceString": "   at System.Linq.ThrowHelper.ThrowNoElementsException()
       at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
       at NPoco.Database.First[T](String sql, Object[] args)
       at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeRepositoryBase`1.PersistUpdatedBaseContentType(IContentTypeComposition entity)
       at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeRepository.PersistUpdatedItem(IContentType entity)
       at Umbraco.Cms.Core.Cache.FullDataSetRepositoryCachePolicy`2.Update(TEntity entity, Action`1 persistUpdated)
       at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.Save(TEntity entity)
       at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeRepositoryBase`1.Move(TEntity moving, EntityContainer container)
       at Umbraco.Cms.Core.Services.ContentTypeServiceBase`2.Move(TItem moving, Int32 containerId)
       at Umbraco.Deploy.Infrastructure.Connectors.ServiceConnectors.ContentTypeConnector.DocumentTypeConnector.MoveContentType(IContentType contentType, Int32 containerId)
       at Umbraco.Deploy.Infrastructure.Connectors.ServiceConnectors.ContentTypeConnector.ContentTypeConnectorBase`2.Process(DeployState state, IDeployContext context, Int32 pass)
       at Umbraco.Deploy.Infrastructure.Connectors.ServiceConnectors.ServiceConnectorBase`3.Process(ArtifactDeployState dart, IDeployContext context, Int32 pass)
       at Umbraco.Deploy.Infrastructure.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)",
```

### Steps to reproduce

Honestly no idea.

### Expected result

It would update the uda file with a description for the property

**Comment by jemayn** [comment]
I haven't seen this other than that one case, and no idea how it happened and it has since resolved itself.
So I will just close this issue 🤷‍♂️
