### ISSUE TITLE
Deploy on Azure Linux shows the "Update Umbraco Schema" process stuck on read pending

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Deploy.Issues#169]
A brief description of the issue goes here.

Clicking on the Update Umbraco Schema button results in the process being stuck on Read pending

Reproduction
------------
### Bug summary

Umbraco version: 11.4.0
Deploy version: 11.1.2

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/56826332/ad2ce00d-39ad-41d7-9379-82e15fc8966f)

### Specifics

Services setup
![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/56826332/fdc2c4fb-5d15-401c-bb0e-872d6c3ecd29)

### Steps to reproduce

1. create the project locally
2. create a linux app service plan + web app + SQL db + SQL server on azure
3. install deploy
4. publish that to azure
5. run the Update Umbraco Schema process via the backoffice 

### Expected result

It completes either with a success or with an error

### Actual result

It just hangs

---
_This item has been added to our backlog [AB#30986](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/30986)_

**Comment by RyuLindow** [comment]
Personally, I get constant spam of 

```
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '@x', line 1, position 573.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(JsonReader reader)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Serilog.Formatting.Compact.Reader.LogEventReader.TryRead(LogEvent& evt)
   at Umbraco.Cms.Core.Logging.Viewer.SerilogJsonLogViewer.TryRead(LogEventReader reader, LogEvent& evt)
```

in the Umbraco logs after pressing the button but a customer who experiences the same Deploy behavior and is on the exact same setup doesn't see this error, so I'm not sure if they're connected.

**Comment by tobijoh** [comment]
Hi,
We have the same problem.
When running TriggerDeploy from our CI/CD pipeline in Azure DevOps the deploy seems to work fine, although the status in the UI doesn’t really seem to reflect what is actually happening.
When triggering a deploy from the UI nothing happens.
It seems that the `deploy` file is created when triggering a deploy, but nothing seems to be reacting on it.

**Comment by AndyButland** [comment]
We've tested a fix for this feature on Linux that will be included with the next set of patch releases and should resolve this issue.
