### ISSUE TITLE
Unable to transfer content nodes with BlockList: NullReferenceException at Umbraco.Deploy.Contrib.Connectors.ValueConnectors.BlockEditorValueConnector.ToArtifact

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Deploy.Issues#173]
In an Umbraco 8 site, I am unable to deploy a content node with BlockList data from local to Dev. The error on failed transfer is:

```
EXCEPTION:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Deploy.Contrib.Connectors.ValueConnectors.BlockEditorValueConnector.ToArtifact(Object value, PropertyType propertyType, ICollection`1 dependencies)
   at Umbraco.Deploy.Contrib.Connectors.ValueConnectors.BlockEditorValueConnector.ToArtifact(Object value, PropertyType propertyType, ICollection`1 dependencies)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.SerializeNonVariantValue(ICollection`1 dependencies, Boolean published, IDictionary`2 propertyCollection, Property property, IValueConnector valueConnector, IContextCache contextCache)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.AddProperty(Property property, ICollection`1 dependencies, Boolean published, IDictionary`2 propertyCollection, IContextCache contextCache)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.MapArtifactProperties(PropertyCollection properties, ICollection`1 dependencies, Boolean published, IContextCache contextCache)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnectorBase.MapVersion(IContent content, ICollection`1 dependencies, Boolean published, IContextCache contextCache)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.GetArtifact(GuidUdi udi, IContent content, IContextCache contextCache)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.GetArtifact(GuidUdi udi, IContextCache contextCache)
   at Umbraco.Deploy.Environments.CurrentEnvironment.GetSignatures(IEnumerable`1 udis, IContextCache contextCache, CancellationToken token)
   at Umbraco.Deploy.Environments.CurrentEnvironment.CreateManifestAsync(Guid sessionId, IEnumerable`1 items, IEnumerable`1 exclude, CancellationToken token)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<CreateManifestOnSource>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ProceedToPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsyncSub>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsyncSub>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteForItems>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteForItems>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__22.MoveNext()
```

To ensure that the two environments were synchronized, I used the Deploy Dashboard locally to "Export Schema", pushed all the files, and ran "Update Schema" on the Dev environment. On Dev, I also ran "Clear Signatures" and "Set Signatures" successfully. Then on Local, I ran "Clear Signatures" successfully, but when I ran "Set Signatures", I got a similar error:

```
{
  "Date": "2023-07-13T17:45:21.207302-04:00",
  "Message": "Object reference not set to an instance of an object.",
  "Ex": {
    "ClassName": "System.NullReferenceException",
    "Message": "Object reference not set to an instance of an object.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at Umbraco.Deploy.Contrib.Connectors.ValueConnectors.BlockEditorValueConnector.ToArtifact(Object value, PropertyType propertyType, ICollection`1 dependencies)\r\n   at Umbraco.Deploy.Contrib.Connectors.ValueConnectors.BlockEditorValueConnector.ToArtifact(Object value, PropertyType propertyType, ICollection`1 dependencies)\r\n   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.SerializeNonVariantValue(ICollection`1 dependencies, Boolean published, IDictionary`2 propertyCollection, Property property, IValueConnector valueConnector, IContextCache contextCache)\r\n   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.AddProperty(Property property, ICollection`1 dependencies, Boolean published, IDictionary`2 propertyCollection, IContextCache contextCache)\r\n   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.MapArtifactProperties(PropertyCollection properties, ICollection`1 dependencies, Boolean published, IContextCache contextCache)\r\n   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnectorBase.MapVersion(IContent content, ICollection`1 dependencies, Boolean published, IContextCache contextCache)\r\n   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.GetArtifact(GuidUdi udi, IContent content, IContextCache contextCache)\r\n   at Umbraco.Deploy.Work.WorkItems.SetSignaturesWorkItem.<>c__DisplayClass15_0.<SetSignatures>b__0(Object x)\r\n   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()\r\n   at Umbraco.Deploy.Persistence.SignatureRepository.SetSignatures(IEnumerable`1 signatures)\r\n   at Umbraco.Deploy.SignatureRefresher.SetSignatures(IEnumerable`1 signatures)\r\n   at Umbraco.Deploy.Work.WorkItems.SetSignaturesWorkItem.SetSignatures(IList`1 entities, String entityType, IContextCache contextCache, Nullable`1 pageNumber, Nullable`1 numberOfPages, Nullable`1 totalRecords)\r\n   at Umbraco.Deploy.Work.WorkItems.SetSignaturesWorkItem.SetPagedSignatures(PagedEntitiesGetterDelegate pageEntitiesGetter, String entityType, IContextCache contextCache)\r\n   at Umbraco.Deploy.Work.WorkItems.SetSignaturesWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)\r\n   at Umbraco.Deploy.Work.WorkTask.<RunAsync>d__21.MoveNext()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nToArtifact\nUmbraco.Deploy.Contrib.Connectors, Version=3.0.2.0, Culture=neutral, PublicKeyToken=null\nUmbraco.Deploy.Contrib.Connectors.ValueConnectors.BlockEditorValueConnector\nSystem.String ToArtifact(System.Object, Umbraco.Core.Models.PropertyType, System.Collections.Generic.ICollection`1[Umbraco.Core.Deploy.ArtifactDependency])",
    "HResult": -2147467261,
    "Source": "Umbraco.Deploy.Contrib.Connectors",
    "WatsonBuckets": null
  },
  "Sender": "Umbraco.Deploy.Work.WorkItems.SetSignaturesWorkItem"
}
```

### Things Checked

- The nodes with BlockList open fine in the back-office for editing and there are no Console errors. The pages also display fine on the front-end locally.

- Other content nodes which I have added the BlockList property to also **do not transfer** - whether they have content in the BlockList property or not.

- Other individual nodes without BlockList data **can be transferred** without issue.

### Specifics

- Umbraco Cloud
- Umbraco v 8.18.8
- Deploy 4.8.0
- UmbracoDeploy.Core =  v 4.8.0
- UmbracoDeploy.Contrib = v 4.2.1

### Similar/Related Issues
https://github.com/umbraco/Umbraco.Deploy.Issues/issues/51
https://github.com/umbraco/Umbraco.Cloud.Issues/issues/276

---
_This item has been added to our backlog [AB#31352](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31352)_

**Comment by hfloyd** [comment]
Hoping for a better understanding of where the failure was occurring, I attached a locally "debug-compiled" version of the "UmbracoDeploy.Contrib" (v4/dev branch) to the site and ran the "Set Signatures". It completed without errors.

Then using the newly compiled file locally, I was able to successfully transfer a content node with an empty BlockList property to the Dev environment. 

When I then tried to transfer a node with BlockList content, I got a different error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #4 failed for artifact umb://document/83d8d9531ea74b15a901304ad315f73b.
 On: <umb://document/83d8d9531ea74b15a901304ad315f73b>
Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
-

EXCEPTION:

Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<SucceedOrThrow>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<WaitAction>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<ProcessPackageAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<ProcessPackage>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteForItems>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteForItems>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteForItems>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__21.MoveNext()
```
I then committed and git pushed the two locally-compiled "Umbraco.Deploy.Contrib.Connectors" files (.dll & .pdb).

After that completed, I was able to transfer that node which was previously throwing the error.

So... I'm not sure where this leaves things. My own issue is resolved (for now), but I wonder if a new release needs to be made for Umbraco.Deploy.Contrib.Connectors 4?

**Comment by AndyButland** [comment]
I'll have a look and see if I can replicate, though it's an odd one on the face of it.  What you've seen does look similar to the issues you linked to, but they have been marked as resolved a couple of years ago.

Your testing suggests there's an issue with 4.2.1 but not with the latest code from the repository, however they look to be [exactly the same](https://github.com/umbraco/Umbraco.Deploy.Contrib/compare/release-4.2.1..v4/dev),

**Comment by AndyButland** [comment]
I can't immediately replicate using a new Umbraco 8 site from Umbraco Cloud, and have confirmed it does come with the latest version 4,2,1 of `Umbraco.Deploy.Contrib.Connectors.dll`.

Are you able to share any further replication steps where you see the issue with 4.2.1 please?  Perhaps there's something specific about the set up of the block list.

**Comment by AndyButland** [comment]
OK, will close this then, but of course if you do get a recurrence and are definitely using 4.2.1, please re-open and we can have another look.
