### ISSUE TITLE
Unable to restore or transfer content that has a grid property that content a nested content component following recent upgrade to 8.17.0 and Deploy 4.3.0

### ISSUE THREAD

**Issue by gmulvaneyhc** [umbraco/Umbraco.Deploy.Issues#82]
We upgraded from Umbraco 8.16.0 to 8.17.0.

**UmbracoDeplyo.Contrib - 4.1.0
UmbracoDeploy.Core - 4.3.0
UmbracoDepoy.Forms - 4.3.0
UmbracoDeploy.OnPrem - 4.3.0**

We have documents that use a grid editor, with grid components that use Nested Content and the MultiNodeTreePicker.

We are no longer able to use Umbraco Deploy (standalone) to synchronise all of the content between sites that we host ourselves. It was working fine before we pushed the upgrade - we have republished all of the content on both sites, but it made no difference.

We have been able to synchronise documents that don't have a grid editor, but we have seen deploy fail in two different ways:

- case 1: parsing a document with a nested content element in a grid
- case 2: parsing a document with a dropdown list that was referenced from a MNTP in a grid

**This is the output from case 1**
The source environment has thrown a Umbraco.Deploy.Exceptions.ProcessArtifactException with message: Process pass #4 failed for artifact umb://document/356360b99bad4b17b8705ac4f03d6193. It might have been caused by an inner System.NotSupportedException with message: `Invalid prefix '5', when trying to parse '5'`.

The following artifacts might be involved:

**umb://document/356360b99bad4b17b8705ac4f03d6193**

66a98d92 - Executing, 10% - Get remote session
66a98d92 - Executing, 20% - Create manifest on source
66a98d92 - Executing, 25% - Review manifest on target
66a98d92 - Executing, 25% - Update manifest on source
66a98d92 - Executing, 25% - Review manifest on target
66a98d92 - Executing, 25% - Update manifest on source
66a98d92 - Executing, 25% - Review manifest on target
66a98d92 - Executing, 25% - Update manifest on source
66a98d92 - Executing, 25% - Review manifest on target
66a98d92 - Executing, 25% - Update manifest on source
66a98d92 - Executing, 25% - Review manifest on target
66a98d92 - Executing, 30% - Create package on source
66a98d92 - Executing, 80% - Complete remote session
66a98d92 - Executing, 80% - Process package on target
66a98d92 - Executing, 80% - Exception!
66a98d92 - Executing, 80% - Abort remote session
66a98d92 - Executing, 80% - Restore caches and indexes
66a98d92 - Failed, 80% - Total time 00:00:54.224.

EXCEPTION
 (proper exception traces at the end of this log)
System.NotSupportedException: Invalid prefix '5', when trying to parse '5'.
Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #4 failed for artifact umb://document/356360b99bad4b17b8705ac4f03d6193.
----------------------------------------------------------------

![image](https://user-images.githubusercontent.com/92580616/137480583-4b956d2a-578b-4719-a759-f519c5dadfd1.png)

EXCEPTION:

Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #4 failed for artifact umb://document/356360b99bad4b17b8705ac4f03d6193.
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<ProcessPackage>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetPartialRestoreWorkItem.<Proceed>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetPartialRestoreWorkItem.<ExecuteAsyncSub>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.TargetPartialRestoreWorkItem.<ExecuteAsyncSub>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetPartialRestoreWorkItem.<ExecuteAsync>d__14.MoveNext()

INNER:
  System.NotSupportedException: Invalid prefix '5', when trying to parse '5'.
     at Umbraco.Deploy.Connectors.ValueConnectors.DefaultValueConnector.FromArtifact(String value, PropertyType propertyType, Object currentValue)
     at Umbraco.Deploy.Contrib.Connectors.ValueConnectors.NestedContentValueConnector.FromArtifact(String value, PropertyType propertyType, Object currentValue)
     at Umbraco.Deploy.Contrib.Connectors.GridCellValueConnectors.DocTypeGridEditorCellValueConnector.SetValue(GridControl gridControl)
     at Umbraco.Deploy.Connectors.ValueConnectors.GridValueConnector.FromArtifact(String value, PropertyType propertyType, Object currentValue)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.SetVariantPropertyValue(IDictionary`2 artifactPropertyValues, Property currentProperty, PropertyType propertyType, Boolean currentContentIsPublished)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.UpdatePropertyType(TContent content, IDictionary`2 artifactProperties, Boolean currentContentIsPublished, PropertyType propertyType, IEnumerable`1 cultures)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.MapContentProperties(TContent content, IEnumerable`1 propertyTypes, IDictionary`2 artifactProperties, Boolean currentContentIsPublished)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.Process4(DeployState state, IDeployContext context, Int32 pass)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ServiceConnectorBase`3.Process(ArtifactDeployState dart, IDeployContext context, Int32 pass)
     at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)

----------------------------------------------------------------
----------------------------------------------------------------

**This is the output from case 2**
The source environment has thrown a Umbraco.Deploy.Exceptions.ProcessArtifactException with message: Process pass #4 failed for artifact umb://document/658571b1ae6443f99d3bce4e8fe2ac43. It might have been caused by an inner System.NotSupportedException with message: Invalid prefix '[', when trying to parse '[ "Red" ]'.

The following artifacts might be involved:

**umb://document/658571b1ae6443f99d3bce4e8fe2ac43**

4fe485a2 - Executing, 10%
4fe485a2 - Executing, 10% - Get remote session
4fe485a2 - Executing, 20% - Create manifest on source
4fe485a2 - Executing, 25% - Review manifest on target
4fe485a2 - Executing, 25% - Update manifest on source
4fe485a2 - Executing, 25% - Review manifest on target
4fe485a2 - Executing, 25% - Update manifest on source
4fe485a2 - Executing, 25% - Review manifest on target
4fe485a2 - Executing, 25% - Update manifest on source
4fe485a2 - Executing, 25% - Review manifest on target
4fe485a2 - Executing, 25% - Update manifest on source
4fe485a2 - Executing, 25% - Review manifest on target
4fe485a2 - Executing, 30% - Create package on source
4fe485a2 - Executing, 80% - Complete remote session
4fe485a2 - Executing, 80% - Process package on target
4fe485a2 - Executing, 80% - Exception!
4fe485a2 - Executing, 80% - Abort remote session
4fe485a2 - Executing, 80% - Restore caches and indexes
4fe485a2 - Failed, 80% - Total time 00:00:20.602.

EXCEPTION
 (proper exception traces at the end of this log)

System.NotSupportedException: Invalid prefix '[', when trying to parse '[
  "Red"
]'.

Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #4 failed for artifact umb://document/658571b1ae6443f99d3bce4e8fe2ac43.
----------------------------------------------------------------

![image](https://user-images.githubusercontent.com/92580616/137480060-305aa4a3-8e73-467a-88e0-b01b9d1d9392.png)

EXCEPTION:

Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #4 failed for artifact umb://document/658571b1ae6443f99d3bce4e8fe2ac43.
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<ProcessPackage>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetPartialRestoreWorkItem.<Proceed>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetPartialRestoreWorkItem.<ExecuteAsyncSub>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.TargetPartialRestoreWorkItem.<ExecuteAsyncSub>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetPartialRestoreWorkItem.<ExecuteAsync>d__14.MoveNext()

INNER:
  System.NotSupportedException: Invalid prefix '[', when trying to parse '[
  "Red"
]'.
     at Umbraco.Deploy.Connectors.ValueConnectors.DefaultValueConnector.FromArtifact(String value, PropertyType propertyType, Object currentValue)
     at Umbraco.Deploy.Contrib.Connectors.GridCellValueConnectors.DocTypeGridEditorCellValueConnector.SetValue(GridControl gridControl)
     at Umbraco.Deploy.Connectors.ValueConnectors.GridValueConnector.FromArtifact(String value, PropertyType propertyType, Object currentValue)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.SetVariantPropertyValue(IDictionary`2 artifactPropertyValues, Property currentProperty, PropertyType propertyType, Boolean currentContentIsPublished)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.UpdatePropertyType(TContent content, IDictionary`2 artifactProperties, Boolean currentContentIsPublished, PropertyType propertyType, IEnumerable`1 cultures)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.MapContentProperties(TContent content, IEnumerable`1 propertyTypes, IDictionary`2 artifactProperties, Boolean currentContentIsPublished)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.Process4(DeployState state, IDeployContext context, Int32 pass)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ServiceConnectorBase`3.Process(ArtifactDeployState dart, IDeployContext context, Int32 pass)
     at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)

**Comment by gmulvaneyhc** [comment]
Hey - thank you very much - I really appreciate it!

**Comment by AndyButland** [comment]
Due in the release of Umbraco.Deploy.Contrib 4.1.2, which will be available [here](https://www.nuget.org/packages/UmbracoDeploy.Contrib).
