### ISSUE TITLE
Cache Instructions for front end servers not written upon deployment completion

### ISSUE THREAD

**Issue by darrenferguson** [umbraco/Umbraco.Deploy.Issues#90]
Cache Instructions for front end servers not written upon deployment completion

I am working with Umbraco Deploy on Prem version 4.4.1 and Umbraco 8.17.1

I have 3 x Umbraco instances:

1. Master staging server - Set to be ServerRole.Master
2. Master live server - Set to be ServerRole.Master
3. Replica live server - Set to be ServerRole.Replica

I execute a content deployment from server 1 to server 2 (staging to live). and expect that any content changes are propagated out to server 3.

Through some investigation I can see that:

- umbracoCacheInstruction never gets written to notify server 3 of the change
- post deployment I can attach my debugger to Umbraco and see that the DeliverRemote method in the BatchedDatabaseServerMessenger is invoked.
- This method puts the cache instruction into a list on the current HttpContext which should get flushed by the FlushBatch method - but the hook into that is the UmbracoModule.EndRequest event and Umbraco deploy doesn't appear to execute within the scope of an Umbraco Http Request.
- I can't debug Umbraco deploy as it is obviously closed source/proprietary - but the stack trace is below for detail.

As a workaround - I can create a custom DatabaseServerMessenger which inherits from BatchedDatabaseServerMessenger and overrides the DeliverRemote method.

I can then call the base implementation before calling an explicit base.FlushBatch(); to write the cache instructions to the Umbraco database.

{   at Umbraco.Web.BatchedDatabaseServerMessenger.BatchMessage(ICacheRefresher refresher, MessageType messageType, IEnumerable`1 ids, Type idType, String json)
   at Umbraco.Web.BatchedDatabaseServerMessenger.DeliverRemote(ICacheRefresher refresher, MessageType messageType, IEnumerable`1 ids, String json)
   at WebApplication2.Application.CustomDatabaseServerMessenger.DeliverRemote(ICacheRefresher refresher, MessageType messageType, IEnumerable`1 ids, String json)
   at Umbraco.Core.Sync.ServerMessengerBase.Deliver[TPayload](ICacheRefresher refresher, TPayload[] payload)
   at Umbraco.Core.Sync.ServerMessengerBase.PerformRefresh[TPayload](ICacheRefresher refresher, TPayload[] payload)
   at Umbraco.Web.Cache.DistributedCache.RefreshByPayload[TPayload](Guid refresherGuid, IEnumerable`1 payloads)
   at Umbraco.Web.Cache.DistributedCacheExtensions.RefreshContentCache(DistributedCache dc, TreeChange`1[] changes)
   at Umbraco.Web.Cache.DistributedCacheBinder.ContentService_TreeChanged(IContentService sender, EventArgs args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Umbraco.Web.Cache.DistributedCacheBinder.HandleEvents(IEnumerable`1 events)
   at Umbraco.Deploy.DeployEventDispatcher.ScopeExitCompleted()
   at Umbraco.Core.Events.QueuingEventDispatcherBase.ScopeExit(Boolean completed)
   at Umbraco.Core.Scoping.Scope.<>c__DisplayClass85_0.<RobustExit>b__1()
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.TryFinally(Action[] actions)
   at Umbraco.Core.Scoping.Scope.RobustExit(Boolean completed, Boolean onException)
   at Umbraco.Core.Scoping.Scope.DisposeLastScope()
   at Umbraco.Core.Scoping.Scope.Dispose()
   at Umbraco.Deploy.Core.AltScope.Dispose()
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.<>c__DisplayClass23_0.<Complete>b__0()
   at Umbraco.Deploy.Work.WorkTask.TryDo(Action action)
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.<ExecuteCompleteAction>b__22_0()
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.<>c__DisplayClass30_0.<ExecuteAction>b__0(CancellationToken token)
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.<ExecuteAsync>d__24.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
   at System.Threading.Tasks.AwaitTaskContinuation.ExecuteWorkItemHelper()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
}

**Comment by AndyButland** [comment]
Thanks for reporting and your efforts in debugging this @darrenferguson - I've replicated your setup and can confirm what you've found.  The crux of the issue seems to be that whilst the events are correctly raised by Deploy, when handled in the CMS they are done so within the context of a constructed Umbraco and HTTP context - which is where the batch of instructions are stored (in `HttpContext.Items`).  And then as you've noted, when they are flushed, this is on an Umbraco request and a different `HttpContext`, hence no instructions are found.

I've looked to resolve it via a change in the CMS, as per [this PR](https://github.com/umbraco/Umbraco-CMS/pull/11757).  In my testing this does fix the issue, though I need to see how the approach is considered in review.

Your workaround sounds fine too, though I guess you lose the benefits of the "batching" of these messages, which I imagine is why the `BatchedDatabaseServerMessenger` was introduced (for use over the `DatabaseServerMessenger`),

**Comment by darrenferguson** [comment]
Hi @AndyButland thanks for looking into this and making a PR to fix it in Umbraco.

Our workaround doesn't handle batch "refreshes" as you say, but it isn't a huge issue for us as the volume of publishes is relatively low and usually one item per time.

I'm mainly reporting it as a "good citizen" in case someone else comes up against it in the future!

**Comment by AndyButland** [comment]
And I'm glad you did... definitely something we want to fix up if we can so it works without having to use a workaround.

**Comment by drbldgtl** [comment]
Does the same issue exist in v9?

**Comment by darrenferguson** [comment]
@AndyButland I've found another issue around load balancing and booting in Azure - which is a core issue. What is the best place to have it "discussed" - I can't just supply a fix, as the solution needs some discussion and buy in from the core team, before I do the leg work to create a PR!

**Comment by AndyButland** [comment]
@drbldgtl - not sure yet but I'm investigating that this week too.  Possibly not due to the changes from events --> notifications in V9, but will need to confirm.
@darrenferguson - raise an issue on the [CMS tracker](https://github.com/umbraco/Umbraco-CMS/issues) I think will be best.

**Comment by AndyButland** [comment]
The [PR](https://github.com/umbraco/Umbraco-CMS/pull/11757) fixing this issue has been merged now in the CMS repo, and will be available in a future CMS release - certainly 8.18, and perhaps an earlier patch if one is made available.
