### ISSUE TITLE
Issues with inconsistent and unpredictable Deployments using Deploy 2.x and Umbraco-Cloud

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/Umbraco.Deploy.Issues#93]
Currently using Deploy-2.1.5 for Umbraco-7.15.7 on Umbraco-Cloud.

Pushing a metadata update to the repo, either directly from local-dev to cloud (in my case live) or from baseline-master to child (again, in my case live) does not reliably trigger the Deploy to run, and requires logging into Kudu (which brings its own issues) and then checking the logs to see what's happening, and if not deploying, manually triggering the deploy using echo > deploy from the /data folder.

Then, that inevitably results in an error being logged and a deploy-failed being displayed, claiming the deploy failed because a deploy is already in process - because for some reason it tries to trigger the deploy twice - meaning you now don't have the deploy-progress flag being displayed but instead have a deploy-failed flag displayed, and so have to keep checking the logs to find out what is actually happening and whether or not to manually intervene.

Then, when checking the logs to see what's happening, the reported 'Artifacts' being processed does not typically align to the update that was actually pushed to the repository - suggesting perhaps a failure to clean-up failed or incomplete Deployments, or perhaps referencing completed Deployments?

Finally, as a Deployment is completing, the deploy-completed flag does not always update, and I often encounter a failure to update the Examine Internal Index, leaving it in a corrupt state, and requiring that I intervene after the deployment by manually re-indexing. This is unpredictable, but typically happens more often with larger databases.

Here is an example of pushing a single metadata change (changing the label - name - on a doc-type property).

Note that manual triggering of the deploy was required, then it reports a deploy-failed when it's actually working on it, then it processes 7 artifacts, then it corrupts the Examine Internal-Index before completing. Manual re-indexing of the Examine Internal-Indexer has no issues and fixes the problem, but it's obviously a requirement that is unexpected.

```
 date time [server] INFO  Umbraco.Deploy.Work.WorkEnvironment - Beginning deployment dff0a3fb-479c-49a6-8620-7e6bf846e646.
 date time [server] INFO  Umbraco.Deploy.Disk.DiskService - File watcher Changed event triggered for 'deploy' and processed.
 date time [server] INFO  Umbraco.Deploy.Disk.DiskService - File watcher Changed event triggered for 'deploy-complete' and processed.
 date time [server] INFO  Umbraco.Deploy.Disk.DiskService - Triggered (deploy)
 date time [server] INFO  Umbraco.Deploy.Disk.DiskService - File watcher Changed event triggered for 'deploy-progress' and processed.
 date time [server] INFO  Umbraco.Deploy.Work.WorkEnvironment - Beginning deployment d352da31-1755-40bc-b7ff-744f749c94e0.

---- Multiple deployments triggered ----
 date time [server] ERROR Umbraco.Deploy.Disk.DiskService - Failed.
Umbraco.Deploy.Exceptions.EnvironmentBusyException: The environment is busy with a deployment try again later
   at Umbraco.Deploy.Work.WorkEnvironment.Begin(IWorkItem work, TimeSpan timeout)
   at Umbraco.Deploy.Disk.DiskService.Process(String statePath, String trigger, ILoggingWorkItem work, Boolean canRetry)
----

 date time [server] INFO  Umbraco.Web.Suspendable+ScheduledPublishing - Suspend scheduled publishing.
 date time [server] INFO  Umbraco.Deploy.WorkItems.DiskReadWorkItem - Preparing
 date time [server] INFO  Umbraco.Deploy.Disk.DiskService - Completed (deploy)
 date time [server] INFO  Umbraco.Deploy.WorkItems.DiskReadWorkItem - Reading state
 date time [server] INFO  Umbraco.Deploy.Disk.DiskService - File watcher Changed event triggered for 'deploy-progress' and processed.
 date time [server] INFO  Umbraco.Deploy.Disk.DiskService - File watcher Changed event triggered for 'deploy-failed' and processed.
 date time [server] INFO  Umbraco.Deploy.WorkItems.DiskReadWorkItem - Detecting collisions within 589 artifacts
 date time [server] INFO  Umbraco.Deploy.WorkItems.DiskReadWorkItem - Reviewing 589 artifacts
 date time [server] INFO  Umbraco.Deploy.WorkItems.DiskReadWorkItem - Processing 7 artifacts
 date time [server] INFO  Umbraco.Web.Suspendable+PageCacheRefresher - Suspend document cache.
 date time [server] INFO  Umbraco.Web.Suspendable+PageCacheRefresher - Suspend document cache.
 date time [server] INFO  Umbraco.Web.Suspendable+ExamineEvents - Suspend indexers.
 date time [server] INFO  Umbraco.Deploy.WorkItems.DiskReadWorkItem - Commit
 date time [server] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 date time [server] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 date time [server] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ICacheRefresher
 date time [server] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ICacheRefresher (took 1ms)
 date time [server] INFO  Umbraco.Deploy.WorkItems.DiskReadWorkItem - Restore caches and indexes
 date time [server] INFO  Umbraco.Web.Suspendable+ScheduledPublishing - Resume scheduled publishing.
 date time [server] INFO  Umbraco.Web.Suspendable+PageCacheRefresher - Resume document cache (reload:true).
 date time [server] INFO  umbraco.content - Loading content from database...
 date time [server] INFO  Umbraco.Web.Suspendable+ExamineEvents - Resume indexers (rebuild:true).
 date time [server] INFO  UmbracoExamine.DataServices.UmbracoLogService - Rebuilding index, Provider=InternalMemberIndexer, NodeId=-1
 date time [server] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - member, Provider=InternalMemberIndexer, NodeId=-1
 date time [server] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - member, took 157ms, Provider=InternalMemberIndexer, NodeId=-1
 date time [server] INFO  UmbracoExamine.DataServices.UmbracoLogService - Rebuilding index, Provider=InternalIndexer, NodeId=-1
 date time [server] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - content, Provider=InternalIndexer, NodeId=-1
 date time [server] INFO  umbraco.content - Save Xml to file...
 date time [server] INFO  umbraco.content - Saved Xml to file.

 ---- Examine Internal-Index is now corrupt ----
 date time [server] WARN  Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedMediaCache - Failed (10 times) to retrieve medias from Examine index and had to load them from DB. This may indicate that the Examine index is corrupted.**
 date time [server] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - content, took 53210ms, Provider=InternalIndexer, NodeId=-1
----

 date time [server] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - media, Provider=InternalIndexer, NodeId=-1
 date time [server] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - media, took 22011ms, Provider=InternalIndexer, NodeId=-1
 date time [server] INFO  UmbracoExamine.DataServices.UmbracoLogService - Rebuilding index, Provider=ExternalIndexer, NodeId=-1
 date time [server] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - content, Provider=ExternalIndexer, NodeId=-1
 date time [server] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - content, took 487ms, Provider=ExternalIndexer, NodeId=-1
 date time [server] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - media, Provider=ExternalIndexer, NodeId=-1
 date time [server] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - media, took 293ms, Provider=ExternalIndexer, NodeId=-1
 date time [server] INFO  Umbraco.Deploy.WorkItems.DiskReadWorkItem - Complete
 date time [server] INFO  Umbraco.Deploy.Work.WorkEnvironment - Deployment dff0a3fb-479c-49a6-8620-7e6bf846e646 completed.
 date time [server] INFO  Umbraco.Deploy.Disk.DiskService - Completed (deploy)
 date time [server] INFO  Umbraco.Deploy.Disk.DiskService - File watcher Changed event triggered for 'deploy-complete' and processed.
 date time [server] INFO  Umbraco.Deploy.Disk.DiskService - File watcher Changed event triggered for 'deploy-failed' and processed.
```

**Comment by AndyButland** [comment]
Hi @c9mbundy - it looks like you are running into some issues here that we've been working on resolving, and hopefully have done for V8.  There's some differences in behaviour on the new infrastructure and has either caused or revealed two problems:

- Deployments being triggered as part of a git push deployment, that then leads to a site restart and interrupts the pending deployment, leading to some of the issues you've described.
- The monitoring of trigger files in a running application either not firing, or firing more than once.

We're back-porting these to V7 which will be out in the next release, expected early in the new year.

I'll close this and tag it with the release, but obviously if you find issues after installing that please do re-open and let me know.

If you are up for testing out a pre-release version, and then if it looks to help, using in the meantime, please let me know and I can make it available for you next week.
