### ISSUE TITLE
Content Transfer fails when parent and child nodes has role based protection

### ISSUE THREAD

**Issue by jonat123** [umbraco/Umbraco.Deploy.Issues#99]
It's possible to select a child node as Login and Error pages under a role based protected parent node when doing so a transfer or restore is not possible and the environment will throw a `Umbraco.Deploy.Exceptions.GraphException with message: Encountered a cyclic dependency.` Error message

Reproduction
------------
### Bug summary
You can select a child node as Login and Error pages under a role based protected parent node.

an example of this is:

- Parent node (role based protection) 
    - Child node (Login page for ''Parent node'') 
    - Child node (Error page for ''Parent node'')

### Specifics
Tested on the latest version of Umbraco and deploy:

Umbraco 8.6.3
Deploy 3.4.5

Full error message:
```
EXCEPTION:
Umbraco.Deploy.Exceptions.GraphException: Encountered a cyclic dependency.
   at Umbraco.Deploy.Core.TopoGraph`2.Visit(TItem item, ISet`1 visited, TItem[] sorted, Int32& index, Int32 incr, Boolean throwOnCycle, Boolean throwOnMissing)
   at Umbraco.Deploy.Core.TopoGraph`2.Visit(TItem item, ISet`1 visited, TItem[] sorted, Int32& index, Int32 incr, Boolean throwOnCycle, Boolean throwOnMissing)
   at Umbraco.Deploy.Core.TopoGraph`2.Visit(TItem item, ISet`1 visited, TItem[] sorted, Int32& index, Int32 incr, Boolean throwOnCycle, Boolean throwOnMissing)
   at Umbraco.Deploy.Core.TopoGraph`2.GetSortedItems(Boolean throwOnCycle, Boolean throwOnMissing, Boolean reverse)
   at Umbraco.Deploy.Environments.CurrentEnvironment.CreatePackage(Guid sessionId, Manifest manifest)
   at Umbraco.Deploy.Environments.CurrentEnvironment.CreatePackageAsync(Guid sessionId, Manifest manifest, CancellationToken token)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<CreatePackageOnSource>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ProceedToPackage>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsyncSub>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsyncSub>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__15.MoveNext()
```

### Steps to reproduce

1. Create a content node + 2-3 child nodes
2. Set role based protection on parent node - Choose child node as Login page and child node as Error page under public access for the parent node.

Then the Child nodes will now also show as having role based protection:
![image](https://user-images.githubusercontent.com/54025331/85413337-fdf3de00-b56a-11ea-965e-83bd587dfd08.png)

3. Try and transfer the content to the next environment

You will then get the error: 
`Umbraco.Deploy.Exceptions.GraphException with message: Encountered a cyclic dependency.` 

![image](https://user-images.githubusercontent.com/54025331/85413659-60e57500-b56b-11ea-917e-97139c1e49b1.png)

### Expected result
Expected the content to be transfered to the next environment

### Actual result
The transfer fails with an error message and the content will not be transfered.

**Comment by AndyButland** [comment]
I can see why this is happening and detected as a cyclic dependency, which is happening because where the login/no access pages have a dependency on the parent, and the parent has dependencies on them.

I think we can avoid this situation by handling the processing of restricted page dependencies though depending on whether the login/no access pages are children of the restricted page.

A fix is being reviewed and if considered appropriate will be in the next patch releases.

**Comment by AndyButland** [comment]
Due in 4.4.4 and 9.2.3.

**Comment by readingdancer** [comment]
@AndyButland - We have just come across this issue with a site running on 7.15.10 is there a reason why your fix would not be working on this site?

As a back story, the site used to be larger and the secure area was just part of the site, recently a new site launched and this secure area has been moved to it's own sub domain and within Umbraco it is now the root of the site, hence the Login / Error pages have to exist within the secure area. It all seems to work fine, but we have now discovered that the deploy process is failing with the above error.

**Comment by AndyButland** [comment]
It won't be in place on that site no, as Deploy 4 is for Umbraco 8 and above.  So I'm afraid for Umbraco 7, if the issue existed in that, then it wouldn't have received this fix.

**Comment by readingdancer** [comment]
Thanks for the response @AndyButland is this something that could be fixed in the previous version as currently it's preventing our client from deploying their changes.

**Comment by AndyButland** [comment]
We aren't planning on further work on Deploy for Umbraco 7 to be honest, as this has been in a "security only" phase for [some time now](https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/umbraco-7-end-of-life-eol/).  You'll appreciate with now supporting 4 versions and preparing for a 5th in Umbraco 12, there's already quite a bit of effort involved, so we try to draw some lines aligning with the product lifecycle.

Probably best I'd suggest it to reach out to your partner manager.  If it's really blocking a valued partner such as yourselves they may well ask to expedite it.  Which I'm not averse to doing if that's agreed... but just currently from a purely product perspective I have to try to make sure we don't split out focus too wide.
